### ISSUE TITLE
[Enhancement] Add namespaced `Policy` testing in the examples

### ISSUE THREAD

**Issue by nicksome168** [kyverno/website#1173]
### Description

The current doc on [kyverno test CLI](https://kyverno.io/docs/kyverno-cli/#examples) doesn't have any examples for namespaced `Policy`. It would be nice to provide an example such as the following:

```yml
#invalid.yaml
apiVersion: v1
kind: Pod
metadata:
  name: invalid
  namespace: abc
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
```

```yml
#kyverno-test.yaml
apiVersion: cli.kyverno.io/v1alpha1
kind: Test
metadata:
  name: non-priority-test
policies:
  - policy.yaml
resources:
  - invalid.yaml
results:
  - policy: abc/require-labels. #this is particularly quite subtle
    rule: check-team
    resource: invalid
    kind: Pod
    result: fail
```
```yml
#policy.yaml
apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: require-labels
  namespace: abc
spec:
  validationFailureAction: Enforce
  rules:
  - name: check-team
    match:
      any:
      - resources:
          kinds:
          - Pod
    validate:
      message: "label 'team' is required"
      pattern:
        metadata:
          labels:
            team: "?*"
```

### Slack discussion

https://kubernetes.slack.com/archives/CLGR9BJU9/p1708718111535289
