### ISSUE TITLE
[Bug] Data Source Documentation 

### ISSUE THREAD

**Issue by chuasweechin** [kyverno/website#1211]
### Page link

https://kyverno.io/docs/writing-policies/generate/#data-source

### Description

Tested in Kyverno v1.11.4. 

Using the example resource below, the behaviour for `Modify Trigger` for both `Sync and NoSync Effect` is shown to be `Downstream synced` when I test this out. But in the documentation, it says otherwise.
```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: generate-zk-kafka-configmap
spec:
  rules:
  - name: generate-zk-kafka-configmap
    match:
      any:
      - resources:
          kinds:
            - Namespace
          names:
            - sc-gen-test
    generate:
      synchronize: true
      apiVersion: v1
      kind: ConfigMap
      name: zk-kafka-address
      namespace: "{{request.object.metadata.name}}"
      data:
        kind: ConfigMap
        data:
          ZK_ADDRESS: "192.168.10.10:2181,192.168.10.11:2181,192.168.10.12:2181-neogeofigureisgood"
```

### Expected behavior

N.A.
