### ISSUE TITLE
[Enhancement] best-practice tips for writing a mutateExisting rule

### ISSUE THREAD

**Issue by realshuting** [kyverno/website#1245]
### Description

There are some “best practice” to follow when defining a mutateExisting rule - it’d be better to combine rules for the same target Kind to avoid mutation conflicts. For example, if you have two mutateExisting rules adding different annotations to the Configmap, there will be two URs created for adding the annotation for each rule, and it’s likely that the configmap is outdated when the second rule adding the annotation.

To better explain this scenario, I have the following policy with two rules for the configmap in my local test. There were 2 URs created upon configmap’s update, and 3 failures when processing two URs. In the test, both annotations were added successfully after retry, but in worst case scenario, the mutation could fail completely and no desired annotation can be added since there is the max retries ( 3 times) on failures and the UR will be cleaned up.
```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: mutate-existing
spec:
  mutateExistingOnPolicyUpdate: false
  rules:
  
  - name: rule-1
    skipBackgroundRequests: true
    match:
      any:
      - resources:
          kinds:
          - ConfigMap
    exclude:
      any:
      - resources:
          namespaces:
          - kube-system
    mutate:
      targets:
      - kind: ConfigMap
        apiVersion: v1
        preconditions:
          all:
          - key: "{{ target.metadata.labels.\"deployed-by\" || '' }}"
            operator: NotEquals
            value: amy
      patchStrategicMerge:
        metadata:
          (name): "!kube-root-ca.crt"
          annotations:
            +(tracking-id): "new-{{target.metadata.namespace}}-clustername-environment:/{{target.kind}}:{{target.metadata.namespace}}/{{target.metadata.name}}"

  - name: rule-2
    skipBackgroundRequests: true
    match:
      any:
      - resources:
          kinds:
          - ConfigMap
    exclude:
      any:
      - resources:
          namespaces:
          - kube-system
    mutate:
      targets:
      - kind: ConfigMap
        apiVersion: v1
        preconditions:
          all:
          - key: "{{ target.metadata.labels.\"deployed-by\" || '' }}"
            operator: NotEquals
            value: amy
      patchStrategicMerge:
        metadata:
          (name): "!kube-root-ca.crt"
          annotations:
            +(static-label): some-value
```
```
ur-7fkk4   make-all-resources-viewable-by-argo   mutate     ConfigMap      foosource-2    default                         0s
ur-hdlt4   make-all-resources-viewable-by-argo   mutate     ConfigMap      foosource-2    default                         0s
ur-7fkk4   make-all-resources-viewable-by-argo   mutate     ConfigMap      foosource-2    default             Pending     0s
ur-hdlt4   make-all-resources-viewable-by-argo   mutate     ConfigMap      foosource-2    default             Pending     0s
ur-hdlt4   make-all-resources-viewable-by-argo   mutate     ConfigMap      foosource-2    default             Failed      0s
ur-7fkk4   make-all-resources-viewable-by-argo   mutate     ConfigMap      foosource-2    default             Failed      0s
ur-hdlt4   make-all-resources-viewable-by-argo   mutate     ConfigMap      foosource-2    default             Pending     0s
ur-7fkk4   make-all-resources-viewable-by-argo   mutate     ConfigMap      foosource-2    default             Pending     0s
ur-hdlt4   make-all-resources-viewable-by-argo   mutate     ConfigMap      foosource-2    default             Completed   1s
ur-hdlt4   make-all-resources-viewable-by-argo   mutate     ConfigMap      foosource-2    default             Completed   1s
ur-7fkk4   make-all-resources-viewable-by-argo   mutate     ConfigMap      foosource-2    default             Failed      1s
ur-7fkk4   make-all-resources-viewable-by-argo   mutate     ConfigMap      foosource-2    default             Pending     1s
ur-7fkk4   make-all-resources-viewable-by-argo   mutate     ConfigMap      foosource-2    default             Completed   1s
ur-7fkk4   make-all-resources-viewable-by-argo   mutate     ConfigMap      foosource-2    default             Completed   1s
```

Then I combined two rules into one, there was 1 UR created to add two annotations:
```yaml
    mutate:
      targets:
      - kind: ConfigMap
        apiVersion: v1
        preconditions:
          all:
          - key: "{{ target.metadata.labels.\"deployed-by\" || '' }}"
            operator: NotEquals
            value: amy
      patchStrategicMerge:
        metadata:
          (name): "!kube-root-ca.crt"
          annotations:
            +(tracking-id): "{{target.metadata.namespace}}-clustername-environment:/{{target.kind}}:{{target.metadata.namespace}}/{{target.metadata.name}}"
            +(static-label): some-value
```
```
ur-tpb2h   make-all-resources-viewable-by-argo   mutate     ConfigMap      foosource-2    default                         0s
ur-tpb2h   make-all-resources-viewable-by-argo   mutate     ConfigMap      foosource-2    default             Pending     0s
ur-tpb2h   make-all-resources-viewable-by-argo   mutate     ConfigMap      foosource-2    default             Completed   0s
ur-tpb2h   make-all-resources-viewable-by-argo   mutate     ConfigMap      foosource-2    default             Completed   0s
```

### Slack discussion

https://kubernetes.slack.com/archives/CLGR9BJU9/p1715260460611989
