### ISSUE TITLE
[Enhancement] Guidance for generate + mutate

### ISSUE THREAD

**Issue by chipzoller** [kyverno/website#1262]
### Description

Users are often running into difficulties when performing a mutation on or triggered by a Kyverno generate rule, sometimes leading to swings and roundabouts. This causes not only confusion but potentially convoluted or dangerous combinations of rules.

We should add a section to the [mutate docs](https://kyverno.io/docs/writing-policies/mutate/) with guidance on how users can perform a generate + mutate when the generation is performed by Kyverno itself.

**Comment by chipzoller** [comment]
A "standard" generate plus "standard" mutate is fine:

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sync-secrets
spec:
  rules:
  - name: sync-image-pull-secret
    match:
      any:
      - resources:
          kinds:
          - Namespace
    generate:
      apiVersion: v1
      kind: Secret
      name: regcred
      namespace: "{{request.object.metadata.name}}"
      synchronize: true
      clone:
        namespace: default
        name: regcred
  - name: mutate-secret
    match:
      any:
      - resources:
          kinds:
          - Secret
          names:
          - regcred
    mutate:
      patchStrategicMerge:
        metadata:
          labels:
            foo: bar
```

Modifications are needed when there is a "standard" generate + a "mutate existing" rule:

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sync-secrets
spec:
  rules:
  - name: sync-image-pull-secret
    match:
      any:
      - resources:
          kinds:
          - ConfigMap
          names:
          - myconfig
          namespaces:
          - default
    generate:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      name: myfoocr
      synchronize: false
      data:
        metadata:
          labels:
            custom/related-namespace: yidir
        rules:
          - apiGroups:
            - ""
            resources:
            - services
            - endpoints
            - secrets
            verbs:
            - get
            - list
            - watch
  - name: mutate
    match:
      all:
        - resources:
            kinds:
              - ClusterRole
            selector:
              matchLabels:
                custom/related-namespace: "?*"
    mutate:
      targets:
        - apiVersion: v1
          kind: Namespace
          name: "{{ request.object.metadata.labels.\"custom/related-namespace\" }}"
      patchStrategicMerge:
        metadata:
          labels:
            custom/namespace-ready: "true"
```

In such cases, the `--backgroundServiceAccountName` flag will need to be removed/changed on the admission controller's deployment.
