### ISSUE TITLE
[Bug] Incorrect values file example

### ISSUE THREAD

**Issue by andrewjkeith** [kyverno/website#1506]
### Page link

https://kyverno.io/docs/installation/upgrading/#breaking-changes

### Description

The example values file is missing a key: `rbac:`
The example should be something like this:
```
admissionController:
  rbac:
    clusterRole:
      extraResources:
        - apiGroups:
            - '*'
          resources:
            - '*'
          verbs:
            - get
            - list
            - watch
```

### Expected behavior

n/a
