### ISSUE TITLE
Variable substitution failure in precondition MUST be interpreted as empty string

### ISSUE THREAD

**Issue by kacejot** [kyverno/website#231]
Example:
```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  annotations:
    meta.helm.sh/release-name: kyverno-policies      
    meta.helm.sh/release-namespace: kyverno
    pod-policies.kyverno.io/autogen-controllers: none
  labels:
    app.kubernetes.io/managed-by: Helm
  name: if-baltic-restrict-external-load-balancer
spec:
  background: true
  rules:
  - match:
      resources:
        kinds:
        - Service
    name: match-service-type
    preconditions:
    - key: '{{request.object.spec.type}}'
      operator: Equals
      value: LoadBalancer
    validate:
      deny:
        conditions:
        - key: "{{ request.object.metadata.annotations.\"service.beta.kubernetes.io/azure-load-balancer-internal\"}}"
          operator: NotEquals
          value: "true"
  validationFailureAction: enforce
```

Resource:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  selector:
    app: example
  ports:
    - port: 8765
      targetPort: 9376
  type: LoadBalancer
```

In this case `{{ request.object.metadata.annotations.\"service.beta.kubernetes.io/azure-load-balancer-internal\"}}` cannot be resolved and kyverno must interpret it as `""`.
This works only in preconditions and deny.conditions.
