### ISSUE TITLE
Select Resources

### ISSUE THREAD

**Issue by DaviPtrs** [kyverno/website#274]
On https://kyverno.io/docs/writing-policies/match-exclude/#match-statements, the following explanation doesn't match with the provided snippet:

```
In this snippet, the match statement matches on all resources that EITHER have the kind Pod with name “mongodb” OR have the kind Pod and are being created in the “prod” namespace.
```

```
spec:
  rules:
  - name: no-LoadBalancer
    match:
      any:
      - resources:
          kinds: 
          - Service
          names: 
          - "staging"
      - resources:
          kinds: 
          - Service
          namespaces:
          - "prod"

```
