### ISSUE TITLE
[Bug] Document use of match|exclude resource annotations results in no auto-gen

### ISSUE THREAD

**Issue by chipzoller** [kyverno/website#507]
### Page link

https://kyverno.io/docs/writing-policies/autogen/

### Description

"When a name or labelSelector is specified in the match or exclude block, Kyverno skips generating Pod controller rules as these filters may not be applicable to Pod controllers."

Change `labelSelector` to just `selector` and add annotations. Auto-gen rules are skipped when any are true:
1. Name is specified
2. Selector is specified
3. Annotations are specified

### Expected behavior

Acknowledging that having annotations in a match or exclude block will implicitly disable auto-gen.

### Slack discussion

https://kubernetes.slack.com/archives/CLGR9BJU9/p1649164620680119

**Comment by chipzoller** [comment]
Also add how to exclude Pods spawned from excluded controllers by using preconditions. For example:

```yaml
- key: Job
  operator: AnyNotIn
  value: "{{ request.object.metadata.ownerReferences[].kind }}"
```
