### ISSUE TITLE
[Enhancement] Add docs for generateExistingOnPolicyUpdate policies

### ISSUE THREAD

**Issue by prateekpandey14** [kyverno/website#536]
### Description

KDP: https://github.com/kyverno/KDP/pull/10
Implementation: https://github.com/kyverno/kyverno/pull/3819, https://github.com/kyverno/kyverno/pull/3635

## Example Policies

1. This example generate data `NetworkPolicy` to both incoming and existing Namespace with `generateExistingOnPolicyUpdate: true`

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: "..."   
spec:
  background: true
  validationFailureAction: audit
  generateExistingOnPolicyUpdate: true   // trigger generate rule in existing resources
  rules:
  - name: default-deny
    match:
      resources:
        kinds:
        - Namespace
    generate:
      kind: NetworkPolicy
      name: default-deny
      namespace: "{{request.object.metadata.name}}"
      synchronize: true
      data:
        spec:
          # select all pods in the namespace
          podSelector: {}
          # deny all traffic
          policyTypes:
          - Ingress
          - Egress
```

2. This example generate clone `Secret` to both incoming and existing Namespace with `genExisting=true`

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: "..."
spec:
  background: true
  validationFailureAction: audit
  generateExistingOnPolicyUpdate: true   // trigger generate rule in existing resources
  rules:
  - name: sync-image-pull-secret
    match:
      resources:
        kinds:
        - Namespace
    generate:
      apiVersion: v1
      kind: Secret
      name: secret-basic-auth
      namespace: "{{request.object.metadata.name}}"
      synchronize: true
      clone:
        namespace: default
        name: secret-basic-auth
```
