### ISSUE TITLE
[Enhancement] Generate cloning any kind of resources

### ISSUE THREAD

**Issue by franroa** [kyverno/website#587]
### Description

Hi, I was trying to do something like this:
```
  apiVersion: kyverno.io/v1
  kind: ClusterPolicy
  metadata:
    name: sync-instrumentation
    annotations:
      policies.kyverno.io/title: Sync Instrumentation
  spec:
    rules:
    - name: sync-instrumentation
      match:
        resources:
          kinds:
          - Namespace
      generate:
        apiVersion: opentelemetry.io/v1alpha1
        kind: Instrumentation
        name: tempo-instrumentation
        namespace: "test"
        synchronize: true
        clone:
          namespace: default
          name: tempo-instrumentation
```

But it doesn't work. It would be really nice if kyverno could create dynamically resources by checking the fields like we do with kubectl explain

I don't know if that is possible..
Thanks!
