### ISSUE TITLE
[Bug] `path` not documented

### ISSUE THREAD

**Issue by chipzoller** [kyverno/website#589]
### Page link

https://kyverno.io/docs/writing-policies/variables/#variables-from-container-images

### Description

We missed documenting the `path` field in variables from container images.

Ex,,

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: pod-require-non-root-user
spec:
  rules:
    - name: require-non-root-user
      match:
        any:
        - resources:
            kinds:
              - Pod
      context:
      - name: contextVars
        configMap:
          name: kyverno-context-vars
          namespace: default
      mutate:
        foreach:
          - list: request.object.spec.containers
            preconditions:
              all:
                # skip images that are exempt (allowed to run as a root user);
                - key: "{{ images.containers.{{element.name}}.path }}"
                  operator: AnyNotIn
                  value: "{{contextVars.data.exemptRootUserImages}}"
            patchStrategicMerge:
              spec:
                containers:
                  - name: "{{ element.name }}"
                    securityContext:
                      runAsNonRoot: true
```

### Expected behavior

The `path` field shows up and an example value.
