### ISSUE TITLE
[Bug] Invalid values.yaml in kyverno apply docs

### ISSUE THREAD

**Issue by joebowbeer** [kyverno/website#599]
### Page link

https://kyverno.io/docs/kyverno-cli/#apply

### Description

Actual:

```yaml
namespaceSelector:
- name: <namespace1 name>
labels:
  <label key>: <label value>
- name: <namespace2 name>
labels:
  <label key>: <label value>
```

### Expected behavior

```yaml
namespaceSelector:
- name: <namespace1 name>
  labels:
    <label key>: <label value>
- name: <namespace2 name>
  labels:
    <label key>: <label value>
```
