### ISSUE TITLE
[Bug] Documentation is not correct about Policy reports behaviour

### ISSUE THREAD

**Issue by bognarbalazs** [kyverno/website#686]
### Page link

https://kyverno.io/docs/policy-reports/

### Description

In the documentation you can read the following:

Policy reports are Kubernetes Custom Resources, generated and managed automatically by Kyverno, which contain the results of applying matching Kubernetes resources to Kyverno ClusterPolicy or Policy resources. They are created for validate and verifyImages rules when the policy in which they are contained is configured with spec.validationFailureAction: audit **or** spec.background: true and a resource applies to one or more rules according to the policy definition.

### Expected behavior

As I experinced, policy report are generated only if the `spec.validationFailureAction: audit` AND `spec.background: true` AND in the kyverno deployment the `.spec.template.spec.containers[].args` the "--backgroundScan" parameter is not defined and get the default value which is true, or set it to true manually.  

So the "or" is not valid in the documentation,

**Comment by bognarbalazs** [comment]
**UPDATE** refer to slack:

kyverno version: 1.8.1
Used clusterpolicy:
```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-latest-tag
  annotations:
    policies.kyverno.io/title: Disallow Latest Tag
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      The ':latest' tag is mutable and can lead to unexpected errors if the
      image changes. A best practice is to use an immutable tag that maps to
      a specific version of an application Pod. This policy validates that the image
      specifies a tag and that it is not called `latest`.
spec:
  validationFailureAction: audit
  background: false
  failurePolicy: Ignore
  rules:
    - name: require-image-tag
      match:
        resources:
          kinds:
            - Pod
      validate:
        message: "An image tag is required."
        pattern:
          spec:
            containers:
              - image: "*:*"
    - name: validate-image-tag
      match:
        resources:
          kinds:
            - Pod
      validate:
        message: "Using a mutable image tag e.g. 'latest' is not allowed."
        pattern:
          spec:
            containers:
              - image: "!*:latest"
```

kyverno helm values change: 
```yaml
extraArgs:
  - --autogenInternals=true
  - --backgroundScan=false
  - --loggingFormat=json
  - --backgroundScanWorkers=1
  - --admissionReports=false
```

Created pod:
```bash 
k run testpod-latest-2 -n kyverno-test-ns-2 --labels version=latest --image <image repository>/alpine:latest --dry-run=client -o yaml -- tail -f /dev/null
````


If I set the policy to enforce mode, it didn't allow to create the pod, so the policy should work, and I think, it should make a policyreport in audit mode.
