### ISSUE TITLE
[Enhancement] Document `image` variable

### ISSUE THREAD

**Issue by JimBugwadia** [kyverno/website#729]
### Description

Add missing properties, especially `reference`. See here: https://github.com/kyverno/kyverno/blob/9d3b176defe4b7faeb6b4f664e40eef9151cb8a4/pkg/engine/context/context.go#L256

**Comment by JimBugwadia** [comment]
This JMESPath is handy to extract all image references `images.[containers, initContainers, ephemeralContainers][].*.reference[]`

**Comment by Vaani-pathariya** [comment]
hello @JimBugwadia  i am new to kyverno but i think i can contribute to this issue .Also , can you provide me with some resources to understand the project better .
Thank you

**Comment by chipzoller** [comment]
@Vaani-pathariya you realize this is a documentation issue, correct?

**Comment by chipzoller** [comment]
@JimBugwadia please list all missing vars

**Comment by Vaani-pathariya** [comment]
> @Vaani-pathariya you realize this is a documentation issue, correct?

yes , i do

**Comment by Vaani-pathariya** [comment]
> @Vaani-pathariya you realize this is a documentation issue, correct?

Yes i do know that this is a documentation issue . If i am provided with some resources related to the issue , i can work on it .

**Comment by JimBugwadia** [comment]
@Vaani-pathariya thanks for contributing! 

The best way to learn Kyverno is to try it out on your local cluster. Here is the getting started doc:

    https://kyverno.io/docs/introduction/

You can then start reading the developer docs at:

   https://github.com/kyverno/kyverno/blob/main/DEVELOPMENT.md
   
   
To resolve this issue we need to update this section in the docs: 

https://kyverno.io/docs/writing-policies/variables/#variables-from-container-images. 

Here are the changes I suggest:

1. Update the example to add `reference`, `referenceWithTag`, `path` from  https://github.com/kyverno/kyverno/blob/9d3b176defe4b7faeb6b4f664e40eef9151cb8a4/pkg/engine/context/context.go#L256
2. Update the JSON sample to add ephemeral containers 
3. Update examples with how to list all references using the JMESPath sample above

**Comment by chipzoller** [comment]
@JimBugwadia I have tried unsuccessfully to see the value substituted by either `reference` or `referenceWithTag` in my testing, and I used a validate rule both with and without a separate verifyImages rule which mutates tag to digest. In all tests, the var is empty. All other vars substitute correctly. I'm using this to test with my `ghcr.io/chipzoller/zulu` image:

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-labels
spec:
  validationFailureAction: enforce
  rules:
  - name: check-for-labels
    match:
      any:
      - resources:
          kinds:
          - Pod
    validate:
      message: "The var is {{images.containers.zulu.referenceWithTag}}."
      pattern:
        metadata:
          labels:
            app.kubernetes.io/name: "?*"
```
