### ISSUE TITLE
[Bug] Typo in Quick-Start section

### ISSUE THREAD

**Issue by engelju** [kyverno/website#773]
### Page link

https://kyverno.io/docs/introduction/#quick-start

### Description

In the quick start section, in the code describing the ClusterPolicy, there's a typo:

```yaml
kubectl create -f- << EOF
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-labels
spec:
  validationFailureAction: Enforce
  rules:
  - name: check-for-labels
    match:
      any:
      - resources:
          kinds:
          - Pod
    validate:
      message: "label 'app.kubernetes.io/name' is required"
      pattern:
        metadata:
          labels:
            app.kubernetes.io/name: "?*"
EOF
```

When trying to apply this, I get the following error:

```
Error "Unsupported value: "Enforce": supported values: "audit", "enforce"" for field "spec.validationFailureAction".
```

The error message already describes the fix. 😄 The example should be corrected to say ```validationFailureAction: enforce```.

### Expected behavior

ClusterPolicy is being created.
