### ISSUE TITLE
[Bug] Docs should say AND not OR

### ISSUE THREAD

**Issue by chrisshino** [kyverno/website#783]
### Page link

https://kyverno.io/docs/policy-reports/

### Description

It says: 

> They are created for validate and verifyImages rules when the policy in which they are contained is configured with spec.validationFailureAction: Audit **OR** spec.background: true

when in reality it should be:

`They are created for validate and verifyImages rules when the policy in which they are contained is configured with spec.validationFailureAction: Audit **AND** spec.background: true`

### Expected behavior

I would really like it if we could generate reports with Audit mode where spec.background: false, this would help us generate reporting without rate limiting ourselves against our KMS key server.

**Comment by JimBugwadia** [comment]
Hi @chipzoller - was this a recent change?

The behavior in 1.9 for the image verification rule does not seem to match.

**Comment by chipzoller** [comment]
>The behavior in 1.9 for the image verification rule does not seem to match.

In what way?

**Comment by chrisshino** [comment]
It was not generating entrys in the report for. me when I had it set to Audit and background:false, as soon as I switched it to background:true, it started generating

**Comment by chipzoller** [comment]
If background is set to `false` and validationFailureAction is set to `Audit` then the only thing that will cause policy reports to be generated are admission events in accordance with the policy definition. For example, if you have a policy that matches on ConfigMaps and you already have some ConfigMaps which violate the policy at the time you create the policy, with those settings in place only new ConfigMaps created after that point will result in a policy entry.

**Comment by JimBugwadia** [comment]
Yes. This does not seem to be working for image verification policies in audit mode with 1.9, but works for 1.10.

**Comment by chipzoller** [comment]
> Yes. This does not seem to be working for image verification policies in audit mode with 1.9, but works for 1.10.

I cannot confirm this behavior. A verifyImages ClusterPolicy which sets `validationFailureAction=Audit` and `background=false` will generate a report if a failing resource is created. See the following process below.

1, Confirm no PolicyReport exists.
```sh
$ k get polr
No resources found in default namespace.
```

2. Introduce a new ClusterPolicy with background disabled and validationFailureAction set to `Audit`.
```yaml
apiVersion: kyverno.io/v2beta1
kind: ClusterPolicy
metadata:
  name: keyless-mutatedigest-verifydigest-required
spec:
  validationFailureAction: Audit
  webhookTimeoutSeconds: 30
  background: false
  rules:
    - name: check-builder-id-keyless
      match:
        any:
        - resources:
            kinds:
              - Pod
      verifyImages:
      - imageReferences:
        - "ghcr.io/chipzoller/zulu*"
        mutateDigest: true
        verifyDigest: true
        required: true
        attestors:
        - entries:
          - keyless:
              subject: "https://github.com/chipzoller/zulu/.github/workflows/slsa-generic-keyless.yaml@refs/tags/v1*"
              issuer: "https://token.actions.githubusercontent.com"
              rekor:
                url: https://rekor.sigstore.dev
```

```sh
$ k apply -f cpol.yaml 
clusterpolicy.kyverno.io/keyless-mutatedigest-verifydigest-required created
```
3. Run a Pod with this image which DOES violate this ClusterPolicy.
```sh
$ k run zulu --image ghcr.io/chipzoller/zulu:v0.0.14
Warning: policy keyless-mutatedigest-verifydigest-required.check-builder-id-keyless: failed to verify image ghcr.io/chipzoller/zulu:v0.0.14: .attestors[0].entries[0].keyless: subject mismatch: expected https://github.com/chipzoller/zulu/.github/workflows/slsa-generic-keyless.yaml@refs/tags/v1*, received https://github.com/chipzoller/zulu/.github/workflows/slsa-generic-keyless.yaml@refs/tags/v0.0.14
Warning: policy keyless-mutatedigest-verifydigest-required.check-builder-id-keyless: unverified image ghcr.io/chipzoller/zulu@sha256:476b21f1a75dc90fac3579ee757f4607bb5546f476195cf645c54badf558c0db
pod/zulu created
```
4. Wait ~10 seconds, get PolicyReport resources in the same Namespace.
```sh
$ k get polr
NAME                                              PASS   FAIL   WARN   ERROR   SKIP   AGE
cpol-keyless-mutatedigest-verifydigest-required   0      1      0      0       0      4s
```
5. Get intermediary AdmissionReport and BackgroundScanReport and confirm only AdmissionReport entries are generated.
```sh
$ k get admr,bgscanr
NAME                                                              PASS   FAIL   WARN   ERROR   SKIP   AGE
admissionreport.kyverno.io/72be8925-3c43-45c7-9891-79d14d679236   0      1      0      0       0      52s
admissionreport.kyverno.io/89a165fe-df0d-4c01-a446-63afaa8f2303   0      1      0      0       0      52s
```
