### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by lewang321** [kyverno/website#964]
### Page link

https://kyverno.io/docs/writing-policies/verify-images/sigstore/#trust

### Description

Hello Everyone , I want to trust the ca certificate of harbor, I followed the docs as (https://kyverno.io/docs/writing-policies/verify-images/sigstore/#trust ) , and then apply the clusterpolicy as below

```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-image
spec:
  validationFailureAction: enforce
  background: false
  webhookTimeoutSeconds: 30
  failurePolicy: Fail
  rules:
    - name: check-image
      match:
        any:
        - resources:
            kinds:
              - Pod
      verifyImages:
      - imageReferences:
        - "harbor.test/pub/*"
        attestors:
        - count: 1
          entries:
          - keys:
              publicKeys: |-
                -----BEGIN PUBLIC KEY-----
                xxx
                -----END PUBLIC KEY-----             
          
```

I still got the error when apply the yaml of the pod 
```
kubectl apply -f pod-test.yaml 
Error from server: error when creating "pod-test.yaml": admission webhook "mutate.kyverno.svc-fail" denied the request: 

policy Deployment/default/pod-test for resource violation: 

check-image:
  autogen-check-image: "failed to verify image rke-harbor2.cnr.local/pub/net-tools:v5:
    .attestors[0].entries[0].keys: no matching signatures:\nunable to verify bundle:
    retrieving rekor public key: updating local metadata and targets: error updating
    to TUF remote mirror: tuf: failed to download 3.root.json: Get \"https://sigstore-tuf-root.storage.googleapis.com/3.root.json\":
    x509: certificate signed by unknown authority\nremote status:{\n\t\"mirror\":
    \"https://sigstore-tuf-root.storage.googleapis.com\",\n\t\"metadata\": {}\n}"
```
not sure how to resolve it....

Thanks,

### Expected behavior

none
