### ISSUE TITLE
[Enhancement] Add documentation for enabling flexible registry credential configurations

### ISSUE THREAD

**Issue by vishal-chdhry** [kyverno/website#985]
### Description

1.11 adds a new feature where we can set `imageRegistryCredentials ` in `verifyImage` policies that can override the global. 

```yaml
imageRegistryCredentials
   helpers:
   - AWS
   - Azure
   secrets:
   - name: regcred 
```

Issue: https://github.com/kyverno/kyverno/issues/6346
PR: https://github.com/kyverno/kyverno/pull/7114
